import React, { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import './App.css';

function App() {
  const [hasStarted, setHasStarted] = useState(false);
  const [timestamp, setTimestamp] = useState(0);
  const [isPaused, setIsPaused] = useState(false);
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [context, setContext] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  
  const playerRef = useRef(null);

  // Example video ID that typically has captions
  const videoId = 'N3AkSS5hXMA';

  useEffect(() => {
    if (!hasStarted) return;

    const tag = document.createElement('script');
    tag.src = 'https://www.youtube.com/iframe_api';
    document.body.appendChild(tag);

    window.onYouTubeIframeAPIReady = () => {
      playerRef.current = new window.YT.Player('player', {
        videoId: videoId,
        playerVars: {
          autoplay: 1, // Auto-play when they click start on hero
          controls: 1,
        },
        events: {
          onStateChange: (event) => {
            // State 2 is PAUSED
            if (event.data === 2) {
              setTimestamp(Math.floor(playerRef.current.getCurrentTime()));
              setIsPaused(true);
            } else if (event.data === 1) { // State 1 is PLAYING
              setIsPaused(false);
              setAnswer('');
              setContext('');
              setError('');
            }
          },
        },
      });
    };

    return () => {
      // Cleanup script tags if component unmounts
      const scripts = document.querySelectorAll('script[src="https://www.youtube.com/iframe_api"]');
      scripts.forEach(script => script.remove());
    };
  }, [hasStarted, videoId]);

  const ask = async () => {
    if (!question.trim()) return;
    setLoading(true);
    setAnswer('');
    setContext('');
    setError('');

    try {
      const res = await axios.post('http://localhost:5001/ask', {
        videoId,
        timestamp,
        question,
      });
      setAnswer(res.data.answer);
      setContext(res.data.context);
    } catch (err) {
      console.error(err);
      setError(err.response?.data?.error || 'Failed to fetch the answer. Make sure the Flask server is running.');
    } finally {
      setLoading(false);
    }
  };

  const handleStart = () => {
    setHasStarted(true);
  };

  if (!hasStarted) {
    return (
      <div className="landing-page">
        {/* Background Decorative Elements */}
        <div className="bg-orb orb-1"></div>
        <div className="bg-orb orb-2"></div>
        <div className="bg-orb orb-3"></div>

        <div className="landing-container">
          <div className="hero-header slide-up-fade">
            <h1 className="hero-title animate-text-gradient">Pause AI</h1>
            <p className="hero-subtitle">
              Supercharge your learning workflow by asking questions directly against the exact moment you pause a video.
            </p>
            
            <div className="cta-container" style={{ marginTop: '1rem', marginBottom: '2rem' }}>
              <button className="giant-play-button bounce-in" onClick={handleStart} style={{ animationDelay: '0.2s' }}>
                <div className="play-icon"></div>
                <span>Enter Experience</span>
              </button>
              <p className="cta-hint slide-up-fade" style={{ animationDelay: '0.3s' }}>Click to launch the interactive player</p>
            </div>
          </div>

          <div className="features-grid pop-in" style={{ animationDelay: '0.4s' }}>
            <div className="feature-card holographic-glass hover-lift">
              <div className="feature-icon">✨</div>
              <h3>Instant Context</h3>
              <p>Whenever you hit pause, the app instantly securely fetches the exact transcript snippets surrounding your playhead.</p>
            </div>
            
            <div className="feature-card holographic-glass hover-lift">
              <div className="feature-icon">⚡</div>
              <h3>Groq Powered</h3>
              <p>Experience blazing-fast instantaneous answers generated by Groq's Llama 3 models natively integrated into the backend.</p>
            </div>

            <div className="feature-card holographic-glass hover-lift">
              <div className="feature-icon">🎓</div>
              <h3>Deep Learning</h3>
              <p>Say goodbye to rewinding. Ask for clarification on complex topics and learn at your own pace without losing your place.</p>
            </div>
          </div>

          <div className="journey-flow pop-in" style={{ animationDelay: '0.5s' }}>
            <h2 className="section-title">User Journey Flow</h2>
            <div className="journey-steps">
              <div className="step-card">
                <div className="step-number">1</div>
                <h4>Watch & Learn</h4>
                <p>Play embedded educational videos seamlessly.</p>
              </div>
              <div className="step-arrow">➔</div>
              <div className="step-card">
                <div className="step-number">2</div>
                <h4>Pause the Video</h4>
                <p>The app instantly captures your precise timestamp.</p>
              </div>
              <div className="step-arrow">➔</div>
              <div className="step-card">
                <div className="step-number">3</div>
                <h4>Ask a Question</h4>
                <p>Type your doubt directly into the prompt box.</p>
              </div>
              <div className="step-arrow">➔</div>
              <div className="step-card">
                <div className="step-number">4</div>
                <h4>AI Synthesizes</h4>
                <p>Get an intelligent explanation based on the transcript context.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="app-container fade-in-up">
      <header className="header">
        <h1 className="animate-text-gradient">Pause AI</h1>
        <p>Interactive Video Context & Q&A</p>
      </header>

      <main className="layout">
        <section className="video-section">
          <div className="player-wrapper holographic-border">
            <div id="player"></div>
          </div>
        </section>

        <section className="interaction-panel holographic-glass">
          <div className="status-badge">
            <div className={`pulse ${isPaused ? 'paused' : ''}`}></div>
            {isPaused 
              ? `Video Paused explicitly at ${timestamp}s` 
              : 'Playing Video - Pause to ask questions!'}
          </div>

          <div className="input-group">
            <label htmlFor="question">What are you confused about?</label>
            <textarea
              id="question"
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              placeholder="e.g. Can you explain that concept again?"
              disabled={!isPaused || loading}
              className={isPaused ? 'active-textarea' : ''}
            />
          </div>

          <button 
            className="action-button hover-lift"
            onClick={ask} 
            disabled={!isPaused || loading || !question.trim()}
          >
            {loading ? <span className="spinner"></span> : 'Generate Contextual Answer'}
          </button>

          {error && (
            <div className="response-card error-card pop-in">
              <p>{error}</p>
            </div>
          )}

          {answer && (
            <div className="response-card success-card pop-in">
              <h3>✨ AI Explanation</h3>
              <p>{answer}</p>
              
              {context && (
                <div className="context-box slide-down">
                  <h4>Transcript Evaluated:</h4>
                  <p>"{context}"</p>
                </div>
              )}
            </div>
          )}
        </section>
      </main>
    </div>
  );
}

export default App;
